### ISSUE TITLE
Bug: <spath> inside function

### ISSUE THREAD

**Issue by bratter** [lstwn/broot.vim#7]
Hi,

Thanks for putting this together - broot + vim is 👨‍🍳💋!

It looks like 74e1524757ceb8d501f710bd14a9eac62658e7ba introduced a bug. In the following line:

https://github.com/lstwn/broot.vim/blob/74e1524757ceb8d501f710bd14a9eac62658e7ba/plugin/broot.vim#L84

`expand('<sfile>:p')` is called inside a function but `sfile` can only resolve in the main body of a script as per this thread: https://github.com/vim/vim/issues/9178#issuecomment-974887056. This means the generated config winds up in an undefined location - or what happened in my case, directly in `/home`, where it failed.

Fix is simply to pull this line out of the function. Will drop a PR if it works.

Cheers,
Brendan

**Comment by lstwn** [comment]
Hi Brendan!

Good catch, I'm always surprised about these little vim script specialities that break my expectations 😄

Even better that you supplied a PR. Thanks, I'll merge it and add the link to the vim issue you referenced here for my future self.

**Comment by bratter** [comment]
No worries! That behavior seems crazy!
